[package]
name = "wowparser4"
version = "4.0.0"
edition = "2021"

[dependencies]
lazy_static = "1.4"
chrono = "0.4"
termion = "2.0.1"

[build-dependencies]

[profile.release]
opt-level = "z"
debug = false
